<?php

return $data = [
    'companies' => ["Trenitalia", "Italo", "Frecciarossa"],
    'stations' => ["Roma Termini",
    "Milano Centrale",
    "Napoli Centrale",
    "Firenze Santa Maria Novella",
    "Bologna Centrale",
    "Torino Porta Nuova",
    "Napoli Centrale",
    "Salerno",
    "Caserta",
    "Pompei Scavi-Villa dei Misteri",
    "Napoli Afragola",
    "Frattamaggiore",
    "Napoli Mergellina",
    "Torre Annunziata Centrale",
    "Napoli Piazza Garibaldi",
    "Sorrento",
    "Acerra",
    "Nocera Inferiore",
    "Baiano",
    "Scafati",
    "Afragola",
    "Pomigliano d'Arco",
    "Cava de' Tirreni",
    "Nola",
    "Poggiomarino-Sarno",
    "Cancello",
    "Villa Literno",
    "Cimitile",
    "Pietrarsa-San Giorgio a Cremano",
    "Circumvesuviana",
    "Angri",
    "Pomigliano d'Arco-Codola",
    "Ottaviano",
    "Cardito",
    "San Giuseppe Vesuviano",
    "Sarno",
    "Sant'Anastasia",
    "Cancello-Arnone",
    "Vico Equense",
    "Pollena Trocchia",
    "Frattaminore",
    "Santa Maria La Bruna",
    "Pimonte",
    "San Marzano sul Sarno",
    "Mercato San Severino",
    "Ottaviano-San Giuseppe Vesuviano",
    "San Valentino Torio",
    "Curti-Sant'Angelo in Formis",
    "Saviano"]
];

